### ISSUE TITLE
Multiple Suggestions!

### ISSUE THREAD

**Issue by Zuvneyy** [ccrsxx/twitter-clone#11]
- Working Messaging system
- Working Notifications with Verified Tabr
- Seperate Follower List (Followers) and Follower count and same thing with like, rt count, replys etc. (so the count is editable in firebase)
- Fully working settings system
- Ability to sign up with Email and phone number (maybe email verification)
- Have emails linked to accounts and numbers linked to accounts 
- Clickable usernames and hashtags when you put a hashtag or tag someone
- Hashtag system
- Search system
- GIF, Polls, emojis etc for tweets and stuff like that
- Editable tweets 
- Account suspensions, private account
- Gold verified badges, Grey badges and blue badges (Don't use Hero Icon, just copy the actual Twitter SVGs)

I know you are probably already working on a lot of these, but just sending it in in case you forgot some!

**Comment by ccrsxx** [comment]
That’s for sure, not just multiple suggestions, LOL. That’s literally Twitter you just describing. 

How can you go around suggesting those insane suggestions without a second thought? I might understand if those were coming from someone that doesn’t know how to code.

No, I’m not currently making any of those features right now. I’m busy with my work and my portofolio

**Comment by ccrsxx** [comment]
That’s for sure, not just multiple suggestions, LOL. That’s literally Twitter you just describing.

How can you go around suggesting those insane suggestions without a second thought? I might understand if those were coming from someone that doesn’t know how to code. Making those features are complicated and will take a long time.

No, I’m not currently making any of those features right now. I’m busy with my work and my portfolio project.

I’ll probably migrate this project from using Firebase to MongoDB in the future. And probably adds features like quote tweets, notifications, and messages.

If you’re interested in any of these features being added, feel free to submit your pull request.
