### ISSUE TITLE
dev server not running

### ISSUE THREAD

**Issue by piyush168713** [ccrsxx/twitter-clone#12]
https://github.com/ccrsxx/twitter-clone/issues/9#issue-1510281366

After running `npx next dev,` it is  not working.

![error](https://user-images.githubusercontent.com/81097447/226638026-443c9933-9c75-4e20-ac87-9b5298f7a27b.png)

`.env.development`

```
// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "AIzaSy****************8",
  authDomain: "twitter-cl*******.firebaseapp.com",
  projectId: "twitter-clone-*****",
  storageBucket: "twitter-clo****appspot.com",
  messagingSenderId: "1********99",
  appId: "1:1069671**********************de",
  measurementId: "G-J******FL8"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const analytics = getAnalytics(app);
```

also used this config but not working

```
# Dev URL
NEXT_PUBLIC_URL=http://localhost:8080/

# Firebase
NEXT_PUBLIC_API_KEY=AIz*************************M8
NEXT_PUBLIC_AUTH_DOMAIN=twitter-clo**************app.com
NEXT_PUBLIC_PROJECT_ID=twitter-clo**********
NEXT_PUBLIC_STORAGE_BUCKET=twitter-clo*************pot.com
NEXT_PUBLIC_MESSAGING_SENDER_ID=10696**********99
NEXT_PUBLIC_APP_ID=1:106967153**********************9de
NEXT_PUBLIC_MEASUREMENT_ID=G***********L8
```

**Comment by TBNRDev** [comment]
Oh, Hi! To fix this issue, try my own solution.
Go to vercel.app and then sign up with your GitHub account and then deploy your repo. Then put all your token/secret in Tokens/Secrets section. Make sure you use the api name.

**Comment by piyush168713** [comment]
Thankyou @TBNRDev for guiding me.....

https://github.com/piyush168713/twitter-clone
Can you please check the configuration or where eroor occurs in my repo.

Deployement is getting failed in vercel.app
Kindly guide me.

**Comment by ccrsxx** [comment]
Try reinstalling the dependencies again. Delete the `node_modules` and `.next` folder first before installing it.
