### ISSUE TITLE
verify

### ISSUE THREAD

**Issue by retrogamesnetwork** [ccrsxx/twitter-clone#14]
how do i verify users on my own twitter clone

**Comment by Ketchupchh** [comment]
You would have to go to your Firebase storage and set their verified status from there. You can also make an admin settings/commands(?) to do this on your site without having to do login to Firebase each time. Also, make sure to set the admin as your username as the creator has it hardcoded to be his :)

**Comment by ccrsxx** [comment]
There's no way to do it from the front end, It's designed that way. 

You can only verify it by changing the user document's verified field on the Firestore. The user document is located at `/users/{userId}`.
