### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by wabi88** [ccrsxx/twitter-clone#15]
Hello! Love the app, I’m a new self taught “developer”. I’ve cloned and started my own copy but I’m having a couple issues.
Firstly, is made to be deployable by anyone, totally new to all the and GitHub.
Also, I have everything up and running and tweaked it a bit to my liking. Just wondering, how do you assign/give out the Verified Badges?
Thanks again, super appreciate this repository!

**Comment by Ketchupchh** [comment]
This has been answered here: https://github.com/ccrsxx/twitter-clone/issues/14

**Comment by wabi88** [comment]
Sorry, jumped the gun there. Thank you
