### ISSUE TITLE
Site Qustion

### ISSUE THREAD

**Issue by Chat-Globally-Media** [ccrsxx/twitter-clone#17]
So not a bug, but i was wondering if in your free time could you maybe make a step by step tutorial on how to set up our own version of the site because im having a hard time understanding the setup steps as im kinda dumb and usually follow tutorial vids.

**Comment by ccrsxx** [comment]
Sorry, I'm really busy with my uni and work. So no can't do.

But deploying it should be straightforward forward tho. You just need to add the env variable that's in the `env.development` to the Vercel env or you can just dump all the `env.development` to the `env.production`, but this will expose your Firebase API key. 

I suggest you use the former method.
