### ISSUE TITLE
I can't run the server

### ISSUE THREAD

**Issue by vicentefelipechile** [ccrsxx/twitter-clone#20]
When installing the dependencies I get this error message

![imagen](https://github.com/ccrsxx/twitter-clone/assets/70909800/4aa85eac-06cc-47e5-a2a5-71858260afac)
The machine I am using is one based on the ARM architecture.

**Comment by ccrsxx** [comment]
What's not working? looks alright to me.

**Comment by vicentefelipechile** [comment]
My bad this is my output after installing all dependencies

![image](https://github.com/ccrsxx/twitter-clone/assets/70909800/1fd5e454-e0ef-486b-bc1e-5dc84172e5da)

**Comment by ccrsxx** [comment]
Seems the same as this issue #9. It seems that Linux doesn't allow opening port 80. 

A simple fix is by running `npx next dev`, it'll run the dev server with default port 3000. Or by changing the dev script to run the default port by removing `-p 80` here in the package.json. https://github.com/ccrsxx/twitter-clone/blob/f0e162e02930180db5c05a3df229c4180c891536/package.json#L6

**Comment by vicentefelipechile** [comment]
now its working, thank you
