### ISSUE TITLE
Problem with firebase

### ISSUE THREAD

**Issue by minefreak** [ccrsxx/twitter-clone#21]
Hello, 

I can't install the twitter-clone, i get this error using the command: firebase deploy --except functions

Error:

i  deploying storage, firestore

There was an issue deploying your functions. Verify that your project has a Google App Engine instance setup at https://console.cloud.google.com/appengine and try again. If this issue persists, please contact support.

Error: Your project is being set up. Please wait a minute before deploying again.

Having trouble? Try firebase [command] --help

I try very much, but no works.

Thank you for help.

**Comment by ccrsxx** [comment]
This probably happened because you haven't set up one of the needed features of the Firebase. Have you made sure you follow step 5 correctly of the README.md?

![image](https://github.com/ccrsxx/twitter-clone/assets/55032197/eb3170e5-1d81-4bbb-b118-88d9420b8b20)

**Comment by minefreak** [comment]
Now, is return this error:

![image](https://github.com/ccrsxx/twitter-clone/assets/23356723/815c39f3-0bbb-4b75-bb2c-a0df815ce652)

**Comment by minefreak** [comment]
![image](https://github.com/ccrsxx/twitter-clone/assets/23356723/52f2beec-4019-4b9f-bea1-b0bc27924da4)

**Comment by Ketchupchh** [comment]
Looks like you didn't setup your firebase [ENVs](https://github.com/ccrsxx/twitter-clone/blob/main/.env.development)?

**Comment by minefreak** [comment]
> Looks like you didn't setup your firebase [ENVs](https://github.com/ccrsxx/twitter-clone/blob/main/.env.development)?

I have it fully configured....

**Comment by Ketchupchh** [comment]
Your error is saying the opposite. Maybe you've messed up somewhere?

**Comment by minefreak** [comment]
> Your error is saying the opposite. Maybe you've messed up somewhere?

This is my config:

![image](https://github.com/ccrsxx/twitter-clone/assets/23356723/58bfd768-214a-44e8-af0f-bb14c3058edf)

**Comment by Ketchupchh** [comment]
Yea it looks fine to me. No idea what would be causing it then as I've never encountered this myself. Have you checked to see if you saved the .env.development file with the configured values before running the project? Only thing that comes to my head right now lol.

**Comment by minefreak** [comment]
> Yea it looks fine to me. No idea what would be causing it then as I've never encountered this myself. Have you checked to see if you saved the .env.development file with the configured values before running the project? Only thing that comes to my head right now lol.

I will reinstall everything from 0 and try to follow all the steps again, so I can configure it. I really appreciate your help in everything! Thank you very much, when I do the installation again, I will reply.

**Comment by minefreak** [comment]
Hello!

Now it's working, thank you so much for help all!
