### ISSUE TITLE
Feature: Enabling Local Emulator for Firebase for local development

### ISSUE THREAD

**Issue by Goku-kun** [ccrsxx/twitter-clone#22]
Hi, @ccrsxx !

This is a fantastic project that you've created. If you're open to receiving contributions, I'd like to add Firebase emulator as a development mode so that the project can be fully developed locally and people can play with Firebase functions without needing to update to the Blaze plan to deploy the functions.

Great work with the project and maintenance!

**Comment by ccrsxx** [comment]
Hey, glad you enjoyed the project!

Sure, I'm up for contributions. I haven't actually tried it myself tho. If you wanna make a pr for it, that'd be awesome. Just remember to add the step on how to do it in the readme.

Just a heads up - I'm pretty busy with work right now, so I might not get to review and merge it soon.

**Comment by Goku-kun** [comment]
Cool, understood. I'll get started on that and add the documentation for that as well.
