### ISSUE TITLE
Selfhost

### ISSUE THREAD

**Issue by ilomon10** [ccrsxx/twitter-clone#24]
Hey @ccrsxx your project is awesome, UI implementation is close to the original, plus the animations make it more interactive to use.

I'm planning to modify this project with a custom adapter for the backend and am willing to host it on my own server, so I need your permission to use it.

Thankyou

**Comment by ccrsxx** [comment]
It's alright, happy to see you like the project. You're allowed to use it in any way you want since this project is under MIT License.
I'd appreciate it if you can mention me or the repo somewhere in your project tho.

**Comment by ilomon10** [comment]
I will inform you when the site is up, thankyou 👍🏻

**Comment by ilomon10** [comment]
Anyway, i just view your account, terlihat bahwa Anda tinggal di Indonesia. Salam kenal teman 👋🏻.

**Comment by ccrsxx** [comment]
Nice, salam kenal juga. Goodluck sama project-nya hehe.
