### ISSUE TITLE
Can't upload .png

### ISSUE THREAD

**Issue by Fortr4n** [ccrsxx/twitter-clone#27]
Hello I am having trouble expanding file support to support .png do I got to edit the firebase or storage rules?

**Comment by ccrsxx** [comment]
It's already supported. Here's the validation file that's used in the project that allows `.png` image support:

https://github.com/ccrsxx/twitter-clone/blob/47f1780ae0dff1c77c5d7dddf501ca8e2a5a259a/src/lib/validation.ts#L4-L16

You can even test it yourself here on https://twitter-clone-ccrsxx.com.
