### ISSUE TITLE
Running to  xampp page

### ISSUE THREAD

**Issue by Rivalakmalll** [ccrsxx/twitter-clone#30]
hi first its great source i like it and i learn everything but i have some issue when i run with npm run dev it will give me to local but the local going to xampp pages how i can make it run to  twitter page?? pls answer this thx

**Comment by ccrsxx** [comment]
Just change the below line of code to another port that's not occupied, `3000` should usually be fine.
https://github.com/ccrsxx/twitter-clone/blob/326dd1f4d21f1b52d14272c2239d246c6975af0c/package.json#L7

**Comment by Rivalakmalll** [comment]
where i can find that code in file? and just chat that right for NEXT_PUBLIC_URL=http://localhost not get change any?

**Comment by Rivalakmalll** [comment]
> Just change the below line of code to another port that's not occupied, `3000` should usually be fine.
> 
> https://github.com/ccrsxx/twitter-clone/blob/326dd1f4d21f1b52d14272c2239d246c6975af0c/package.json#L7

**Comment by Rivalakmalll** [comment]
im alrd try too in firebase but i got this how to fix this? @ccrsxx 
![Cuplikan layar 2023-10-13 171337](https://github.com/ccrsxx/twitter-clone/assets/147071945/1603b1e4-4c97-45e9-a671-6366e4ae3a1b)

**Comment by ccrsxx** [comment]
that's weird, are you sure you're in localhost and the dev server is running?

**Comment by Rivalakmalll** [comment]
Im alrd can run in local but its not work for firebase like up screenshot  i give

**Comment by ccrsxx** [comment]
Can you give me the screenshot of the terminal and the browser dev console? Firebase hosting shouldn't show up, it should be the next js web on the localhost.

**Comment by Rivalakmalll** [comment]
@ccrsxx  
![Cuplikan layar 2023-10-13 204758](https://github.com/ccrsxx/twitter-clone/assets/147071945/84f537a0-723e-4e2d-9e00-b1a2c803ac8e)
 here for example

**Comment by ccrsxx** [comment]
Hmm, it seems that you haven't set up the firestore and its region. The step is here:

![image](https://github.com/ccrsxx/twitter-clone/assets/55032197/23aa6ee8-2b25-48ba-8377-d4f93f1ea0bb)

Make sure you set that up and it should work.

Sure here's my Discord username @ccrsxx.

**Comment by Rivalakmalll** [comment]
I do add u like yesterday my username discord are @rival_akmal7 check it
