### ISSUE TITLE
Unhandled Runtime Error FirebaseError: Failed to get document because the client is offline.

### ISSUE THREAD

**Issue by messi06** [ccrsxx/twitter-clone#31]
Unhandled Runtime Error
FirebaseError: Failed to get document because the client is offline.
![2023-10-16_010017](https://github.com/ccrsxx/twitter-clone/assets/13597151/6cd596eb-48b8-4525-8643-079427c09572)

**Comment by DonSenorSombrero** [comment]
How were you able to fix this though? i'm using an emulator
