### ISSUE TITLE
I love you - I have a request

### ISSUE THREAD

**Issue by httptools** [ccrsxx/twitter-clone#38]
The most beautiful, safe and complete Twitter clone in the world is this repository. Thank you for making this beautiful and big tank.

I have two requests. A small request and a big request.

### Small request (please add this quickly):
Notifications!
It's too bad that the user has to check everywhere to see if someone has responded. So please add this section quickly.

### Big request:
Added video upload
Support for correcting tweets, replies, bio
Added search
Add chat (only personal required)
Added mention
Hashtag added
Adding links in the tweet (not mandatory)
Added Explore

**Comment by ccrsxx** [comment]
Duplicated #11 #16.

In a nutshell, I'm extremely busy right now with work and university. I hardly even spend my time on my personal project right now. 

If you want, you can make those features yourself and contribute the project hehe.
