### ISSUE TITLE
[Function request] some suggestions

### ISSUE THREAD

**Issue by baka-9** [ccrsxx/twitter-clone#39]
good job! Thank you for creating this repository
very perfect!
But I have some suggestions
Add video upload
Other login methods: such as email login
....

**Comment by Ketchupchh** [comment]
Video uploads are already implemented but is impossible to do since it's locked behind image checks. You would have to modify some things around to allow video uploads but it's done [here](https://github.com/ccrsxx/twitter-clone/blob/main/src/lib/firebase/utils.ts#L141). You could probably easy integrate email logins since firebase has support for it.

**Comment by baka-9** [comment]
Okay, thank you for the reminder, but I am a programming novice and know nothing about this.....

**Comment by Ketchupchh** [comment]
I see. You could do something like this: 

`export type FileData = {
  src: string;
  alt: string;
  type: string;
};

export type FilesData = (File & { src: string})[];

export type FilesPreview = FileData[];`

`export async function uploadFiles(
  userId: string,
  files: File[]
): Promise<FilesPreview | null> {
  if (!files.length) return null;

  const filesPreview = await Promise.all(
    Array.from(files).map(async (file) => {
      let src: string;

      const { name: alt, type } = file;

      const storageRef = ref(storage, `files/${userId}/${alt}`);

      try {
        src = await getDownloadURL(storageRef);
      } catch {
        await uploadBytesResumable(storageRef, file);
        src = await getDownloadURL(storageRef);
      }

      return { src, alt, type };
    })
  );

  return filesPreview;
}`

This should work.

**Comment by baka-9** [comment]
OMG thank you very much!

**Comment by baka-9** [comment]
OMG,thank you very much!

**Comment by Ketchupchh** [comment]
No problem. If you need any more additional help regarding this project you can message me on Discord: @ketchupch

**Comment by baka-9** [comment]
all right...I tried this code, but it doesn't seem to work?
I can't select the video when I click to upload the image...

Okay..I'll add you on Discord later

**Comment by Ketchupchh** [comment]
This is because you still have the image checks in place. I'll walk you through it on Discord.

**Comment by baka-9** [comment]
It seems that I can't add you as a friend through the Discord link in your README...it jumps directly to the Discord home page.

Sorry I don't know how to use Discord..

**Comment by baka-9** [comment]
Okay...I sent a friend request using your usernameI sent a friend request using your username

**Comment by ccrsxx** [comment]
@Ketchupchh Thanks for the help. 

@baka-9 Thanks for the issue too, I'm really busy with my uni rn, so no I couldn't add the above features.

I will do it probably in the future, no promises tho.

I'm closing this issue, feel free to reopen or create a new issue if you have another problem.
