### ISSUE TITLE
Are users keyed by username?

### ISSUE THREAD

**Issue by stanbar** [ccrsxx/twitter-clone#41]
Hi,
Thank you for sharing this code. I highly appreciate it. I would love to inspire and build my website on top of this codebase.

I wonder why do you check whether the document keyed by `username` exists in the user collection if it's always stored with `uid`

You check whether the `username` exists:
https://github.com/ccrsxx/twitter-clone/blob/c6bf6fba409cbff2ae57bc8069f1e00a202853a0/src/lib/context/auth-context.tsx#L68-L74

And then store user keyed by `uid` 
https://github.com/ccrsxx/twitter-clone/blob/c6bf6fba409cbff2ae57bc8069f1e00a202853a0/src/lib/context/auth-context.tsx#L106

Why do you check whether there exists an document keyed by the `username`? 
Shouldn't you query based on the child element`username` in the collection, instead of the `key`?

I believe you intended to implement it like this

```ts
      const randomUserSnapshot = await getDocs(
        query(usersCollection, where('username', '==', randomUsername))
      );
      if (randomUserSnapshot.empty) available = true;
```

**Comment by Ketchupchh** [comment]
I'm not sure if I get exactly what you're asking (I have not been to sleep in a long time) but the code you're referencing is to check if there's a user in the database that already goes by that username. They're shouldn't be duplicate usernames in the database. Correct me if I didn't fully understand your question, sorry.

**Comment by stanbar** [comment]
@Ketchupchh  Haha, no problem 😄 

My point is that you are checking `username` uniqueness on the document's key level. Instead you should check it on the document's `username` field level.

Wrong:

Good:
```ts
      const randomUserSnapshot = await getDocs(
        query(usersCollection, where('username', '==', randomUsername))
      );
      if (randomUserSnapshot.empty) available = true;
```

**Comment by Ketchupchh** [comment]
Oh I get what you're saying now. I definitely would've done the latter. I'm quite new to Firestore but I think it probably just boils down to preference atp no? Unless @ccrsxx had reason for doing it the way he did(?)

I know he's a busy fella so if he wants to make the change I'm more than happy to add it to my [pull request](https://github.com/ccrsxx/twitter-clone/pull/40).

**Comment by stanbar** [comment]
@Ketchupchh 
Actually I found another problem with the file id. It's present in your PR as well https://github.com/ccrsxx/twitter-clone/issues/42

**Comment by ccrsxx** [comment]
@stanbar Good catch, that's definitely a bug. I didn't realize that the id for the user on firestore is using guid instead of username. 

Thanks @Ketchupchh for the fix on the PR.
