### ISSUE TITLE
promise.all

### ISSUE THREAD

**Issue by jdgamble555** [ccrsxx/twitter-clone#5]
You should probably use `batch` here (and in other places) instead of `Promise.all`.

https://github.com/ccrsxx/twitter-clone/blob/d8bd4018c941b0a1390977e84ad9c8d1745ad058/lib/firebase/utils.ts#L98

Great clone btw!

J

**Comment by ccrsxx** [comment]
Thanks for noticing that. I think using batch would be much cleaner. I'll see what I can do later!
