### ISSUE TITLE
Add emoji 

### ISSUE THREAD

**Issue by pedro-vicente** [ccrsxx/twitter-clone#51]
This interface looks fantastic. Do you have any idea how to change it, to add emoji in the input dialog? Currently, a stop sign is displayed when trying to click the emoji link. Thanks

**Comment by Ketchupchh** [comment]
You get the red "not allowed" sign because this kind of feature isn't implemented. You can implement this feature yourself and open a PR if you'd like :). There are many packages you can install from npm that allows you to make one.

**Comment by pedro-vicente** [comment]
> You get the red "not allowed" sign because this kind of feature isn't implemented

I understand that. I was asking what would be needed to implemented it in Next.JS. I know absolutely nothing about Next.JS, so I am asking for a tutorial, sample code that you can point to, thanks

**Comment by Ketchupchh** [comment]
I haven't implemented one myself which is why I suggested using an npm package. I found [this one](https://www.npmjs.com/package/emoji-picker-react). It comes with documentation and sample code for you as well.

**Comment by pedro-vicente** [comment]
👍🏾

**Comment by ccrsxx** [comment]
Hmm, cool small feature. but no plan to do this since I'm really busy rn. You can try to implement it yourself or maybe even make PR yourself, so I can review it and merge it to this project.

**Comment by pedro-vicente** [comment]
@ccrsxx   My goal here was to adapt this library as a GUI front end for a large C++ back end, that is itself a twitter like engine. This interface looked ideal to adapt (by embedding it inside a C++ web engine) , but at this time I am not sure if it is worth the time. I might prefer a 100% C++ solution, where the support for emoji rendering is also possible, but nothing like this library in widgets, like 'like' posts, retweet, etc. I might get back to this, if the other solution is not possible, thanks for the offer

**Comment by pedro-vicente** [comment]
@ccrsxx So, Javascript is really not for me, and I decided to redo your code in C++. I have a GUI already, so that's not an issue. What I am trying to figure out is the navigation algorithm you did. By that , I mean the all Twitter experience (well, not all) of browsing, responses, etc.

The effect I want is exactly like this interface. 

Here's what I have 

a feed entry displays a "tweet"; 
it has text, images, media, a list of responses , list of likes, retweets

a feed entry has 2 states :
1) regular mode: a regular entry in the feed, an element in the feed list 
2) active mode: after mouse click, covers all feed area, displays responses
3) a stack is made to return to original post; this feed is added to stack, 
4) add a "<- Home" at top, to return to original post (regular  mode) 
5) click on a response, puts that feed in active mode, and adds it to the stack 

Any comments/help on this ?

Gracias
