### ISSUE TITLE
[FEATURE] Change some things

### ISSUE THREAD

**Issue by indra87g** [ccrsxx/twitter-clone#52]
I want some changes for this project:
- Don't use the Twitter logo and name anymore, to prevent copyright problems. We recommend using a newer logo and name.
- Add "explore" feature
- Add "list" feature
- Add more embed options for posts (like GIFs, Polls and So On)
- Add option to delete account permanently

I know it won't be easy, but the contributors to this project, including me, will always support this project.

That is all and thank you

**Comment by Ketchupchh** [comment]
This is a Twitter clone and not it's own thing so I don't think we'd want to change the name and icon. As for everything else, you can add these yourself and open a PR. My DMs are always open if you get stuck :)

**Comment by indra87g** [comment]
fine if it's like that. That is all and thank you
