### ISSUE TITLE
[FEATURE] [BUG]

### ISSUE THREAD

**Issue by ikiitech** [ccrsxx/twitter-clone#55]
- Add another login method, maybe GitHub. Change apple login to github😁
- You can see in picture

![Screenshot (17)](https://github.com/ccrsxx/twitter-clone/assets/139623252/f3929310-68ad-419f-a515-9d9f158cb993)

**Comment by ikiitech** [comment]
(recommended) add logout session

**Comment by Ketchupchh** [comment]
The owner is far too busy to add new features to the repo so you can always make the changes yourself and open a PR :)

How did you get the error? I've never seen this.

**Comment by ikiitech** [comment]
Hello, I'm a beginner who is learning the world of programming

**Comment by Ketchupchh** [comment]
This is a great repo to help you learn. I would suggest spending some time with the project and figuring out how exactly everything works while doing outside study as well.

Once again, if you can, can you tell me how the error occurred that you attached? Did you simply click the log out button or were there certain steps?
