### ISSUE TITLE
Google sign-in method stuck when logging in

### ISSUE THREAD

**Issue by agakcw12** [ccrsxx/twitter-clone#7]
![image](https://user-images.githubusercontent.com/103521917/204033271-2d162ad4-f465-4207-bf01-95b794eca59d.png)

**Comment by ccrsxx** [comment]
Have you created your Firestore database and Cloud storage?

**Comment by agakcw12** [comment]
![image](https://user-images.githubusercontent.com/103521917/204068758-030ced9f-280e-40a2-b493-d5f6d61a9dd6.png)
![image](https://user-images.githubusercontent.com/103521917/204068804-210f5cce-4529-4c73-8260-324024acae0d.png)

this?

**Comment by agakcw12** [comment]
![image](https://user-images.githubusercontent.com/103521917/204068829-a5884d27-afe7-45f0-8cf3-220adec12b1c.png)
![image](https://user-images.githubusercontent.com/103521917/204068840-483d4048-0dd5-464a-8237-72b8398607be.png)

this?

**Comment by agakcw12** [comment]
Already fix, but i have problem

Uploading Desktop 2022.11.26 - 09.45.43.02.DVR_Trim.mp4…

**Comment by agakcw12** [comment]
already fix, but i have another problem
https://user-images.githubusercontent.com/103521917/204069624-92072c88-2322-4810-a8eb-e80aa881e072.mp4

**Comment by agakcw12** [comment]
any solution?

**Comment by ccrsxx** [comment]
> already fix, but i have another problem
> https://user-images.githubusercontent.com/103521917/204069624-92072c88-2322-4810-a8eb-e80aa881e072.mp4
> 
> 

Have you enabled the Google sign in method? It seems that you haven't enabled it.

**Comment by agakcw12** [comment]
![image](https://user-images.githubusercontent.com/103521917/204069964-514316fa-8d7f-4d22-91be-83c7c16d9b47.png)

Already enabled

**Comment by ccrsxx** [comment]
Please share a screenshot of the console inside the chrome dev tool when you try to log in.

**Comment by FNaF1Door** [comment]
how did u fix it
