### ISSUE TITLE
infinite scroll

### ISSUE THREAD

**Issue by THaetami** [ccrsxx/twitter-clone#8]
assalamu'alaikum pak/bu,..
website saya -> https://pengepulaksara.com itu punya fitur infinite scroll, cuma gak berfungsi ketika dibuka di web browser mobile, perkiraan karna tab url browsernya yg gk fixed. mungkin bpk/ibu bisa ngasih masukan atau referensi..
terimakasih :)

**Comment by ccrsxx** [comment]
Wah banyak faktor sih itu. Gk mungkin mekanisme-nya sama seperti project ini. Dari pengetesan saya bisa kok itu di web situs-nya buat infinite scroll-nya di mobile sama desktop.

Klo misalnya gk bisa di mobile biasanya fungsi buat trigger nambah item-nya gk kedeteksi di mobile ya. Mungkin bisa dibaca [ini](https://web.dev/patterns/web-vitals-patterns/infinite-scroll/infinite-scroll/) referensi tentang infinite scroll.

Saran saya kalau mau nanya tentang sesuatu bisa langsung dm saya aja di [Discord](https://discord.com/users/414304208649453568) atau [Twitter](https://twitter.com/ccrsxx). Disini tempatnya buat open issue atau nanya sesuatu khusus buat project ini ya.

**Comment by ccrsxx** [comment]
Saya close ya issue-nya, klo mau lanjut bisa kontak diatas.

**Comment by THaetami** [comment]
baik, terimakasih atas responya pak/bu,.. besok2 saya akan bertanya di twitter :)
