### ISSUE TITLE
Can't run dev server

### ISSUE THREAD

**Issue by TBNRDev** [ccrsxx/twitter-clone#9]
![image](https://user-images.githubusercontent.com/108610517/209462411-f23354b0-01ec-4a6b-9e53-936853b8e4cf.png)

**Comment by ccrsxx** [comment]
Try changing the localhost port. by default, I set the port to be 80. Try running `npx next dev`, it'll change the port to be 3000.

**Comment by TBNRDev** [comment]
> Try changing the localhost port. by default, I set the port to be 80. Try running `npx next dev`, it'll change the port to be 3000.

thanks, I fixed it, also is there a way to remove some components like trending tab or something?

**Comment by ccrsxx** [comment]
To remove components from the layout, you can edit the file at https://github.com/ccrsxx/twitter-clone/blob/main/components/layout/common-layout.tsx. Just find the components that you want to remove and delete or comment out the code.

I'm closing this issue now. If you have any other questions or run into any other issues, raise another issue or just hit me up on Discord or Twitter.
